name: release

on:
  push:
    tags:
      # CalVer tags created by `just bump` (e.g. 2026.8.2)
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  release:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/webology/
    permissions:
      id-token: write # mandatory for Trusted Publishing
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - run: uv sync --locked --python 3.13

      - run: uv run pytest

      - run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
